replicaCount: 1

image:
  repository: ""
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

env: []

ingress:
  enabled: false
  className: "nginx"
  host: ""
  path: "/"
  pathType: "Prefix"

livenessProbe:
  httpGet:
    path: /manage/health
    port: 8080
  initialDelaySeconds: 15
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /manage/health
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10

resources: {}